### ISSUE TITLE
Integrate profile service (S)

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/kernel-legacy#194] opened 2019-05-23 19:33 UTC
Why? 

To help users manage their identity through different devices we need to sync profile data with our profile service. 

What? 

- [ ] Fetch user's profile from profile service
- [ ] Create a sync strategy for having local and remote information up to date

**Comment by fmiras** [comment] 2019-06-13 19:54
This is too ambiguous, need more definition what does integrate profile service means? fetch the profile info when avatar appears? does this involves more than #215?

**Comment by BrianAmadori** [comment] 2019-06-13 20:58
I think this may be a duplicate of #214 or vice-versa.

**Comment by moliva** [comment] 2019-07-29 17:01
This issue depends on the profile service migration.

**Closed as completed** 2019-10-01 16:51 UTC
Labels: blocked
